name: 'Terraform Remote Backend Setup'

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  AWS_REGION: 'eu-north-1'
  S3_BUCKET_NAME: 'your-unique-terraform-state-bucket'
  DYNAMODB_TABLE_NAME: 'terraform-state-locks'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # First try the modern approach with AWS SDK v3
      - name: Configure AWS Credentials (Modern)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # Fallback method if the modern approach fails
      - name: Configure AWS CLI (Fallback)
        if: ${{ failure() }}
        run: |
          mkdir -p ~/.aws
          echo "[default]" > ~/.aws/credentials
          echo "aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
          echo "aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials
          echo "region=${{ env.AWS_REGION }}" >> ~/.aws/credentials

      - name: Verify AWS Credentials
        run: |
          aws sts get-caller-identity
          aws s3 ls || echo "S3 access failed - check permissions"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform-backend-setup

      - name: Terraform Plan
        run: |
          terraform plan \
            -var="aws_region=${{ env.AWS_REGION }}" \
            -var="s3_bucket_name=${{ env.S3_BUCKET_NAME }}" \
            -var="dynamodb_table_name=${{ env.DYNAMODB_TABLE_NAME }}"
        working-directory: ./terraform-backend-setup

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve
        working-directory: ./terraform-backend-setup
